name: flexwala
description: "Flexwala - High quality branding templates."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  dio: ^5.10.0
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.1
  flutter_secure_storage: ^10.3.1
  connectivity_plus: ^7.2.0
  logger: ^2.7.0
  image_picker: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logopng.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logopng.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logopng.png
    - assets/images/topappbarpng.png
